# Generated by Django 4.2.4 on 2023-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='Artist_Table',
        ),
    ]
