# Generated by Django 4.2.4 on 2023-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='qrcode/')),
            ],
        ),
    ]
