# Generated by Django 4.2.4 on 2023-10-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_qrcodeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qrcode/')),
            ],
        ),
        migrations.DeleteModel(
            name='QRCodeEntry',
        ),
    ]
