# Generated by Django 4.2.4 on 2023-10-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_delete_qrcodemodel_alter_artist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('interest', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('JP', 'Japan'), ('IN', 'India')], max_length=100)),
            ],
        ),
    ]
