# Generated by Django 4.2.4 on 2023-10-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
        migrations.AlterModelTable(
            name='persons',
            table='Person_Table',
        ),
    ]
