# Generated by Django 4.2.4 on 2023-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='rid',
            field=models.IntegerField(),
        ),
    ]
