# Generated by Django 4.2.4 on 2023-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reports_rid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reports',
            table='Reports_Table',
        ),
    ]
