# Generated by Django 4.2.4 on 2023-09-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reports_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='aemail',
            field=models.EmailField(max_length=100),
        ),
    ]
