# Generated by Django 4.2.4 on 2023-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(max_length=100)),
                ('pmethod', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=25)),
                ('contact', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
