# Generated by Django 4.2.4 on 2023-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cid_alter_customer_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer_Table',
        ),
    ]
