# Generated by Django 4.2.4 on 2023-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cname',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
