# Generated by Django 4.2.4 on 2023-09-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_cname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.CharField(max_length=255)),
                ('name_of_product', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase', models.DateField()),
                ('category', models.CharField(choices=[('abstract', 'Abstract'), ('technology', 'Technology'), ('digital', 'Digital')], max_length=20)),
            ],
        ),
    ]
